- grafana_dashboard_sync:
    path: "{{ grafana_dashboards_local_path }}"
    name: "{{ inventory_hostname }}"
    url: "{{ grafana_url }}"
    username: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
  register: result
  
- debug: var=result
