- copy:
    content: "{ \"dashboard\": {{ dashboards_to_upload[item].dashboard|to_json }}, \"overwrite\": false }"
    dest: /Users/rbelyakovsky/ansible/tv-dashboards/upload.json
  connection: local      
  become: no
  
- name: upload dashboards
  uri:
    url: "{{ grafana_url }}/api/dashboards/db"
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    force_basic_auth: yes
    body_format: json
    method: POST
    body: "{ \"dashboard\": {{ dashboards_to_upload[item].dashboard|to_json }}, \"overwrite\": false }"
    return_content: yes
    headers:
      Content-Type: "application/json;charset=UTF-8"
  register: uploaded
  changed_when: no
  failed_when: false

- debug: var=uploaded.json

- debug: msg="{{ 'db/' + uploaded.json.slug + '.json' != dashboards_to_upload[item].path }}"

# - block:
#   - name: fix local name if required
#     copy: src =  {{ grafana_dashboards_local_path }}/{{ dashboards_to_upload[item].path }}
#           dest = {{ grafana_dashboards_local_path }}/db/{{ uploaded.json.slug }}.json
#
#   - name: remove old dashboard
#     file: path={{ grafana_dashboards_local_path }}/{{ dashboards_to_upload[item].path }} state=absent
#
#   when: 'db/' + uploaded.json.slug + '.json' != dashboards_to_upload[item].path
#   connection: local
#   become: no
#
